service: be-clients
frameworkVersion: '3'

provider:
  name: aws
  ecr:
    images:
      be_image:
        path: ./

functions:
  app:
    image:
      name: be_image
    timeout: 30
    environment:
      API_KEY: T6QSkXHpA1C6cL3nJhtGdYRTMTXHF3H8GPH19qo0iYsbqss