service: be-clients
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  ecr:
    images:
      saveImage:
        path: ./
functions:
  save:
    image: 727881289392.dkr.ecr.us-east-1.amazonaws.com/lambda-be:latest
