service: be-clients
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  ecr:
    images:
      saveImage:
        path: ./
functions:
  hello:
    handler: app.lambda_handler
